export enum StoreName {
	logger = "logger",
	project = "ProjectStore",
	organization = "OrganizationStore",
	user = "UserStore",
	files = "FileStore",
	manualRun = "ManualRunStore",
	cache = "CacheStore",
	templates = "TemplatesStore",
	sharedBetweenProjects = "SharedBetweenProjectsStore",
	tour = "TourStore",
	drawer = "DrawerStore",
	dashboard = "DashboardStore",
	tablePreferences = "TablePreferencesStore",
	buildFiles = "BuildFilesStore",
}
