import {
	IntegrationForTemplates,
	Integrations,
	IntegrationsMap,
	shouldHideIntegration,
	HiddenIntegrationsForTemplates as HiddenIntegrationsMap,
} from "./integrations.enum";
import { IntegrationSelectOption } from "@src/interfaces/components/forms";

import { AKRoundLogo } from "@assets/image";
import {
	AirtableIcon,
	AnthropicIcon,
	AsanaIcon,
	Auth0Icon,
	AwsIcon,
	ConfluenceIcon,
	DiscordIcon,
	GithubCopilotIcon,
	GithubIcon,
	GoogleCalendarIcon,
	GoogleDriveIcon,
	GoogleFormsIcon,
	GoogleGeminiIcon,
	GoogleGmailIcon,
	GoogleSheetsIcon,
	GoogleYoutubeIcon,
	GrpcIcon,
	HttpIcon,
	HubspotIcon,
	JiraIcon,
	KubernetesIcon,
	LinearIcon,
	MicrosoftTeamsIcon,
	NotionIcon,
	OpenAiIcon,
	PipedriveIcon,
	RedditIcon,
	SalesforceIcon,
	SchedulerIcon,
	SlackIcon,
	SqliteIcon,
	TelegramIcon,
	TwilioIcon,
	ZoomIcon,
} from "@assets/image/icons/connections";

const ValidIntegrationsIcons: Record<Integrations, React.ComponentType<React.SVGProps<SVGSVGElement>>> = {
	linear: LinearIcon,
	airtable: AirtableIcon,
	auth0: Auth0Icon,
	asana: AsanaIcon,
	anthropic: AnthropicIcon,
	aws: AwsIcon,
	calendar: GoogleCalendarIcon,
	chatgpt: OpenAiIcon,
	confluence: ConfluenceIcon,
	discord: DiscordIcon,
	drive: GoogleDriveIcon,
	forms: GoogleFormsIcon,
	github: GithubIcon,
	gmail: GoogleGmailIcon,
	youtube: GoogleYoutubeIcon,
	googlegemini: GoogleGeminiIcon,
	jira: JiraIcon,
	sheets: GoogleSheetsIcon,
	slack: SlackIcon,
	twilio: TwilioIcon,
	telegram: TelegramIcon,
	hubspot: HubspotIcon,
	zoom: ZoomIcon,
	salesforce: SalesforceIcon,
	microsoft_teams: MicrosoftTeamsIcon,
	kubernetes: KubernetesIcon,
	reddit: RedditIcon,
	pipedrive: PipedriveIcon,
	notion: NotionIcon,
};

const HiddenIntegrationsIconsForTemplates: Record<
	IntegrationForTemplates,
	React.ComponentType<React.SVGProps<SVGSVGElement>>
> = {
	githubcopilot: GithubCopilotIcon,
	sqlite3: SqliteIcon,
	scheduler: SchedulerIcon,
	http: HttpIcon,
	autokitteh: AKRoundLogo,
	grpc: GrpcIcon,
};

export const IntegrationsIcons = {
	...ValidIntegrationsIcons,
	...HiddenIntegrationsIconsForTemplates,
};
