export const DEFAULT_SERVER_URL = "http://localhost:9980";
export const EXT_PUBLISHER = "undefined_publisher";
export const DEFAULT_SIDEBAR_VIEW_REFRESH_INTERVAL = 1000;
export const DEFAULT_PROJECT_VIEW_REFRESH_INTERVAL = 1000;
export const DEFAULT_PROJECT_VIEW_SESSION_LOG_REFRESH_INTERVAL = 1000;
export const DEFAULT_ENVIRONMENT = "default";
export const DEFAULT_CONNECTION_TEST_INTERVAL = 5000;
export const DEFAULT_CONNECTION_TEST_SLOW_INTERVAL = 300000;
