export const defalutFileExtension = ".star";

export const monacoLanguages = {
	".bat": "batch",
	".c": "c",
	".cmd": "batch",
	".cpp": "cpp",
	".cs": "csharp",
	".css": "css",
	".dockerfile": "dockerfile",
	".f": "fsharp",
	".f90": "fsharp",
	".fs": "fsharp",
	".go": "go",
	".gradle": "groovy",
	".groovy": "groovy",
	".h": "cpp",
	".htm": "html",
	".html": "html",
	".ini": "ini",
	".java": "java",
	".js": "javascript",
	".json": "json",
	".jsx": "javascript",
	".kt": "kotlin",
	".less": "less",
	".m": "objective-c",
	".md": "markdown",
	".php": "php",
	".pl": "perl",
	".properties": "properties",
	".py": "python",
	".r": "r",
	".rb": "ruby",
	".sass": "sass",
	".scss": "scss",
	".sh": "shell",
	".sql": "sql",
	".star": "python",
	".swift": "swift",
	".ts": "typescript",
	".tsx": "typescript",
	".vue": "html",
	".xml": "xml",
	".yaml": "yaml",
	".yml": "yaml",
};
