export enum PageTitles {
	Base = "base",
	Home = "home",
	Welcome = "welcome",
	Events = "events",
	Settings = "settings",
	NotFound = "404",
	Intro = "intro",
	Chat = "chat",
	Ai = "ai",
	ProjectAssets = "project-assets",
	ProjectCode = "project-code",
	ProjectEvents = "project-events",
	ProjectConnections = "project-connections",
	ProjectTriggers = "project-triggers",
	ProjectVariables = "project-variables",
	ProjectDeployments = "project-deployments",
	ProjectSessions = "project-sessions",
}
