// Asana icon taken from here: https://github.com/detain/svg-logos/blob/master/svg/a/asana-logo.svg under MIT license
export { default as AsanaIcon } from "@assets/image/icons/connections/Asana.svg?react";
// Taken from: https://www.svgrepo.com/svg/442923/brand-auth0
export { default as Auth0Icon } from "@assets/image/icons/connections/Auth0.svg?react";
export { default as AwsIcon } from "@assets/image/icons/connections/Aws.svg?react";
export { default as ConfluenceIcon } from "@assets/image/icons/connections/Confluence.svg?react";
export { default as DiscordIcon } from "@assets/image/icons/connections/Discord.svg?react";
export { default as GithubIcon } from "@assets/image/icons/connections/Github.svg?react";
export { default as GithubCopilotIcon } from "@assets/image/icons/connections/GithubCopilot.svg?react";
export { default as GoogleCalendarIcon } from "@assets/image/icons/connections/GoogleCalendar.svg?react";
export { default as GoogleDriveIcon } from "@assets/image/icons/connections/GoogleDrive.svg?react";
export { default as GoogleFormsIcon } from "@assets/image/icons/connections/GoogleForms.svg?react";
export { default as GoogleGeminiIcon } from "@assets/image/icons/connections/GoogleGemini.svg?react";
export { default as GoogleGmailIcon } from "@assets/image/icons/connections/GoogleGmail.svg?react";
export { default as GoogleSheetsIcon } from "@assets/image/icons/connections/GoogleSheets.svg?react";
export { default as GoogleYoutubeIcon } from "@assets/image/icons/connections/GoogleYoutube.svg?react";
export { default as GrpcIcon } from "@assets/image/icons/connections/Grpc.svg?react";
export { default as HttpIcon } from "@assets/image/icons/connections/Http.svg?react";
// Taken from: https://www.svgrepo.com/svg/443148/brand-hubspot
export { default as HubspotIcon } from "@assets/image/icons/connections/Hubspot.svg?react";
export { default as JiraIcon } from "@assets/image/icons/connections/Jira.svg?react";
export { default as OpenAiIcon } from "@assets/image/icons/connections/chatgpt.svg?react";
export { default as RedisIcon } from "@assets/image/icons/connections/Redis.svg?react";
export { default as SchedulerIcon } from "@assets/image/icons/connections/Scheduler.svg?react";
export { default as SlackIcon } from "@assets/image/icons/connections/Slack.svg?react";
export { default as SqliteIcon } from "@assets/image/icons/connections/Sqlite.svg?react";
export { default as TwilioIcon } from "@assets/image/icons/connections/Twilio.svg?react";
// Taken from: https://www.svgviewer.dev/s/401523/telegram
export { default as TelegramIcon } from "@assets/image/icons/connections/Telegram.svg?react";
// Taken from: https://www.svgrepo.com/svg/452140/zoom
export { default as ZoomIcon } from "@assets/image/icons/connections/Zoom.svg?react";
// Taken from: https://www.svgrepo.com/svg/501547/empty
export { default as EmptyCircleIcon } from "@assets/image/icons/connections/EmptyCircle.svg?react";
// Taken from: https://www.svgrepo.com/svg/333141/linear
export { default as LinearIcon } from "@assets/image/icons/connections/linear.svg?react";
// Taken from https://svgmix.com/item/zglqJw/salesforce
export { default as SalesforceIcon } from "@assets/image/icons/connections/Salesforce.svg?react";
// Taken from: https://www.svgrepo.com/svg/452111/teams
export { default as MicrosoftTeamsIcon } from "@assets/image/icons/connections/MicrosoftTeams.svg?react";
// Taken from: https://iconduck.com/icons/94534/kubernetes
export { default as KubernetesIcon } from "@assets/image/icons/connections/Kubernetes.svg?react";
// Taken from: https://icons.getbootstrap.com/icons/anthropic/
export { default as AnthropicIcon } from "@assets/image/icons/connections/Anthropic.svg?react";
// Taken from: https://www.iconpacks.net/free-icon/reddit-circle-logo-16620.html
// Terms: https://www.iconpacks.net/terms/
export { default as RedditIcon } from "@assets/image/icons/connections/Reddit.svg?react";
// Pipedrive icon https://drive.google.com/drive/folders/1Tc48Ffe7BwE7tKv239aA_ENXnG9cG3v0 + https://www.pipedrive.com/en/newsroom/press-kit
export { default as PipedriveIcon } from "@assets/image/icons/connections/Pipedrive.svg?react";
// Notion icon based on MIT licensed sources generated by Cursor
export { default as NotionIcon } from "@assets/image/icons/connections/Notion.svg?react";
