name: "Setup Test Environment"
description: "Sets up the test environment including Docker container"

inputs:
    descope-project-id:
        description: "Descope project ID"
        required: true
    browser:
        description: "Browser to test"
        required: true
    autokitteh-image:
        description: "AutoKitteh Docker image"
        required: true

runs:
    using: "composite"
    steps:
        - name: Start AutoKitteh container
          shell: bash
          env:
              DESCOPE_PROJECT_ID: ${{ inputs.descope-project-id }}
          run: |
              echo "Starting AutoKitteh container..."
              
              # Start docker command in background and get its PID
              CONTAINER_ID=$(timeout 900 docker run -d \
                -p 9980:9980 \
                -e AK_AUTHHTTPMIDDLEWARE__USE_DEFAULT_USER="false" \
                -e AK_AUTHLOGINHTTPSVC__DESCOPE__ENABLED="true" \
                -e AK_HTTP__CORS__ALLOWED_ORIGINS="http://localhost:8000" \
                -e AK_AUTHSESSIONS__ALLOWED_CORS_COOKIE="true" \
                -e AK_AUTHLOGINHTTPSVC__DESCOPE__PROJECT_ID="$DESCOPE_PROJECT_ID" \
                -e AK_AUTHSESSIONS__COOKIE_KEYS="78d85f1c9fd9df7d3d459a75f1db315ef634dc854ba90bc5add3e6cb6f135bd6,d9591b1ab2d0e5de1fef96a5a8a50b883430884211f16a206f84ad57897f99d5" \
                -e AK_AUTHJWTTOKENS__HMAC__SIGN_KEY="183b1c8f4c64b3450907b3859be0b94044d3c92a3116f02213585a85dd0cb154" \
                -e AK_AUTHJWTTOKENS__ALGORITHM="hmac" \
                ${{ inputs.autokitteh-image }} up --mode=dev --config db.seed_commands="insert into orgs(created_by, created_at, org_id, display_name, updated_by, updated_at) values('7bcbb000-0000-0000-0000-000000000000', '2025-01-06 09:47:45.348066+00:00', '01943b03-6344-702a-9471-1b0098752177', 'Tests''s Personal Org', '00000000-0000-0000-0000-000000000000', '2025-01-06 11:47:45.348369+02:00');insert into users(user_id, email, display_name, created_by, created_at, default_org_id, updated_by, updated_at,status) values('01943b03-6345-7606-8e13-e319ae2f1929', 'test@autokitteh.com', 'Tests User', '7bcbb000-0000-0000-0000-000000000000', '2025-01-06 09:47:45.349399+00:00', '01943b03-6344-702a-9471-1b0098752177', '00000000-0000-0000-0000-000000000000', '2025-01-06 11:47:45.349424+02:00',1);insert into org_members(created_by, created_at, org_id, user_id, status) values('00000000-0000-0000-0000-000000000000', '2025-01-06 11:47:45.350038+02:00', '01943b03-6344-702a-9471-1b0098752177', '01943b03-6345-7606-8e13-e319ae2f1929',1);") || {
                echo "Container startup failed or timed out after 900 seconds (15 minutes)"
                exit 1
              }
              echo "CONTAINER_ID=$CONTAINER_ID" >> $GITHUB_ENV
              echo "AutoKitteh container started successfully with ID: $CONTAINER_ID"

        - name: Setup logging
          shell: bash
          run: |
              docker logs -f ${{ env.CONTAINER_ID }} > docker-logs.txt &
              echo "LOGS_PID=$!" >> $GITHUB_ENV

        - name: Wait for Backend
          shell: bash
          run: |
              source "${{ github.action_path }}/scripts/progress-bar.sh"

              URL=http://localhost:9980
              echo "Waiting for AutoKitteh backend to start..."
              TIMEOUT=300  # 5 minutes timeout
              ITERATIONS=$((TIMEOUT / 2))

              for ((i=1; i<=ITERATIONS; i++)); do
                if curl --output /dev/null --silent --head --fail -X POST $URL; then
                  printf "\r✅ AutoKitteh backend ready in $((i * 2)) seconds!                                          \n"
                  break
                fi

                if [[ -t 1 ]]; then
                  ProgressBar ${i} ${ITERATIONS} "AutoKitteh"
                else
                  echo "Waiting for AutoKitteh... ($((i * 2))s elapsed)"
                fi

                if [ $i -eq $ITERATIONS ]; then
                  printf "\n❌ Timeout waiting for backend after $TIMEOUT seconds\n"
                  exit 1
                fi

                sleep 2
              done

        # - name: Install browser-specific dependencies
        #   if: inputs.browser == 'Safari'
        #   shell: bash
        #   run: npx playwright install-deps webkit

        - name: Install browser-specific dependencies
          shell: bash
          run: |
              if [ "${{ inputs.browser }}" == "Safari" ]; then
                echo "Installing WebKit dependencies for Safari..."
                npx playwright install-deps webkit
              elif [ "${{ inputs.browser }}" == "Firefox" ]; then
                echo "Installing Firefox dependencies..."
                npx playwright install-deps firefox
              else
                echo "No additional dependencies needed for ${{ inputs.browser }}"
              fi
