name: "Setup Test Environment"
description: "Sets up the test environment including Docker container"

inputs:
    descope-project-id:
        description: "Descope project ID"
        required: true
    browser:
        description: "Browser to test"
        required: true
    autokitteh-image:
        description: "AutoKitteh Docker image"
        required: true

runs:
    using: "composite"
    steps:
        - name: Start AutoKitteh container
          shell: bash
          env:
              DESCOPE_PROJECT_ID: ${{ inputs.descope-project-id }}
          run: |
              echo "Starting AutoKitteh container..."
              
              # Use host network mode so the job container can reach it via localhost
              CONTAINER_ID=$(timeout 900 docker run -d \
                --restart unless-stopped \
                --network host \
                -e AK_AUTHHTTPMIDDLEWARE__USE_DEFAULT_USER="false" \
                -e AK_AUTHLOGINHTTPSVC__DESCOPE__ENABLED="true" \
                -e AK_HTTP__CORS__ALLOWED_ORIGINS="http://localhost:8000" \
                -e AK_AUTHSESSIONS__ALLOWED_CORS_COOKIE="true" \
                -e AK_AUTHLOGINHTTPSVC__DESCOPE__PROJECT_ID="$DESCOPE_PROJECT_ID" \
                -e AK_AUTHSESSIONS__COOKIE_KEYS="78d85f1c9fd9df7d3d459a75f1db315ef634dc854ba90bc5add3e6cb6f135bd6,d9591b1ab2d0e5de1fef96a5a8a50b883430884211f16a206f84ad57897f99d5" \
                -e AK_AUTHJWTTOKENS__HMAC__SIGN_KEY="183b1c8f4c64b3450907b3859be0b94044d3c92a3116f02213585a85dd0cb154" \
                -e AK_AUTHJWTTOKENS__ALGORITHM="hmac" \
                ${{ inputs.autokitteh-image }} up --mode=dev --config db.seed_commands="insert into orgs(created_by, created_at, org_id, display_name, updated_by, updated_at) values('7bcbb000-0000-0000-0000-000000000000', '2025-01-06 09:47:45.348066+00:00', '01943b03-6344-702a-9471-1b0098752177', 'Tests''s Personal Org', '00000000-0000-0000-0000-000000000000', '2025-01-06 11:47:45.348369+02:00');insert into users(user_id, email, display_name, created_by, created_at, default_org_id, updated_by, updated_at,status) values('01943b03-6345-7606-8e13-e319ae2f1929', 'test@autokitteh.com', 'Tests User', '7bcbb000-0000-0000-0000-000000000000', '2025-01-06 09:47:45.349399+00:00', '01943b03-6344-702a-9471-1b0098752177', '00000000-0000-0000-0000-000000000000', '2025-01-06 11:47:45.349424+02:00',1);insert into org_members(created_by, created_at, org_id, user_id, status) values('00000000-0000-0000-0000-000000000000', '2025-01-06 11:47:45.350038+02:00', '01943b03-6344-702a-9471-1b0098752177', '01943b03-6345-7606-8e13-e319ae2f1929',1);") || {
                echo "Container startup failed or timed out after 900 seconds (15 minutes)"
                exit 1
              }

              # Verify container started
              sleep 2
              CONTAINER_STATE=$(docker inspect --format='{{.State.Running}}' $CONTAINER_ID 2>/dev/null || echo "false")
              if [ "$CONTAINER_STATE" != "true" ]; then
                echo "❌ Container exited immediately after start"
                echo "=== Container inspect ==="
                docker inspect $CONTAINER_ID || echo "Container not found"
                echo ""
                echo "=== Container logs ==="
                docker logs $CONTAINER_ID || echo "No logs available"
                exit 1
              fi
              echo "CONTAINER_ID=$CONTAINER_ID" >> $GITHUB_ENV
              echo "AutoKitteh container started successfully with ID: $CONTAINER_ID"

        - name: Setup logging
          shell: bash
          run: |
              docker logs -f ${{ env.CONTAINER_ID }} > docker-logs.txt &
              echo "LOGS_PID=$!" >> $GITHUB_ENV
        - name: Wait for Backend
          shell: bash
          run: |
              # With --network host, the container binds directly to the host's localhost
              URL=http://localhost:9980/readyz
              echo "Waiting for backend to start..."
              echo "Testing URL: $URL"
              echo "Container ID: ${{ env.CONTAINER_ID }}"
              TIMEOUT=420  # 7 minutes timeout
              ELAPSED=0

              # Give container a moment to fully start
              sleep 5

              echo ""
              echo "Waiting for 200 OK response..."
              until $(curl --output /dev/null --silent --fail $URL); do
                # Check if container is still running
                CONTAINER_STATE=$(docker inspect --format='{{.State.Running}}' ${{ env.CONTAINER_ID }} 2>/dev/null || echo "false")
                if [ "$CONTAINER_STATE" != "true" ]; then
                  echo ""
                  echo "❌ Container has exited!"
                  echo ""
                  echo "=== Container inspect ==="
                  docker inspect ${{ env.CONTAINER_ID }} | jq '.[0].State' || true
                  echo ""
                  echo "=== Last 200 lines of docker logs ==="
                  docker logs --tail 200 ${{ env.CONTAINER_ID }} || echo "Could not fetch logs"
                  exit 1
                fi

                if [ $ELAPSED -ge $TIMEOUT ]; then
                  echo ""
                  echo "❌ Timeout waiting for backend to start after $TIMEOUT seconds"
                  echo ""
                  echo "=== Final connection attempt details ==="
                  HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" $URL 2>&1 || echo "000")
                  echo "HTTP Status Code: $HTTP_CODE"
                  curl -v $URL 2>&1 || true
                  echo ""
                  echo "=== Container inspect ==="
                  docker inspect ${{ env.CONTAINER_ID }} | jq '.[0].State' || true
                  echo ""
                  echo "=== Network connectivity test from inside container ==="
                  docker exec ${{ env.CONTAINER_ID }} wget -O- http://localhost:9980/readyz 2>&1 || echo "Internal connection failed"
                  echo ""
                  echo "=== Port bindings ==="
                  docker port ${{ env.CONTAINER_ID }} || echo "No port mappings (using host network)"
                  netstat -tuln | grep 9980 || echo "Port 9980 not listening"
                  echo ""
                  echo "=== Last 200 lines of docker logs ==="
                  docker logs --tail 200 ${{ env.CONTAINER_ID }} || echo "Could not fetch logs"
                  exit 1
                fi
                printf '.'
                sleep 2
                ELAPSED=$((ELAPSED + 2))
              done
              echo ""
              echo "✅ Backend is up! (took $ELAPSED seconds)"