name: End-to-End Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Frontend Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Download autokitteh executable
        run: |
          curl -sSL https://get.autokitteh.sh | bash

      - name: Run autokitteh
        env:
          AK_AUTHHTTMIDDLEWARE__REQUIRED: ${{ secrets.AK_AUTHHTTMIDDLEWARE__REQUIRED }}
          AK_AUTHJWTTOKENS__SIGN_KEY: ${{ secrets.AK_AUTHJWTTOKENS__SIGN_KEY }}
          AK_AUTHSESSIONS__ALLOWED_CORS_COOKIE: ${{ secrets.AK_AUTHSESSIONS__ALLOWED_CORS_COOKIE }}
          AK_AUTHSESSIONS__COOKIE_KEYS: ${{ secrets.AK_AUTHSESSIONS__COOKIE_KEYS }}
          AK_HTTP__CORS__ALLOWED_ORIGINS: ${{ secrets.AK_HTTP__CORS__ALLOWED_ORIGINS }}
          AK_AUTHLOGINHTTPSVC__DESCOPE__PROJECT_ID: ${{ secrets.AK_AUTHLOGINHTTPSVC__DESCOPE__PROJECT_ID }}
          AK_AUTHLOGINHTTPSVC__DESCOPE__ENABLED: ${{ secrets.AK_AUTHLOGINHTTPSVC__DESCOPE__ENABLED }}
          AK_AUTHLOGINHTTPSVC__ALLOWED_LOGINS: ${{ secrets.AK_AUTHLOGINHTTPSVC__ALLOWED_LOGINS }}
          AK_AUTHSESSIONS__ALLOWED_DOMAIN: ${{ secrets.AK_AUTHSESSIONS__ALLOWED_DOMAIN }}
        run: |
          ak up --mode=dev &

      - name: Wait for Backend to Start
        run: |
          URL=http://localhost:9980
          echo "Waiting for backend to start..." 
          until $(curl --output /dev/null --silent --head --fail -X POST $URL); do
            printf '.'
            sleep 5
          done
          echo "Backend is up!"

      - name: Run Playwright tests
        env:
          VITE_DESCOPE_PROJECT_ID: ${{ secrets.VITE_DESCOPE_PROJECT_ID }}
        run: |
          git submodule update --init
          npx playwright test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
