import { Integrations } from "@src/enums/components";

import {
	AsanaIntegrationAddForm,
	AnthropicIntegrationAddForm,
	Auth0IntegrationAddForm,
	AwsIntegrationAddForm,
	ConfluenceIntegrationAddForm,
	DiscordIntegrationAddForm,
	GithubIntegrationAddForm,
	GoogleCalendarIntegrationAddForm,
	GoogleFormsIntegrationAddForm,
	GoogleGeminiIntegrationAddForm,
	GoogleIntegrationAddForm,
	HubspotIntegrationAddForm,
	JiraIntegrationAddForm,
	LinearIntegrationAddForm,
	OpenAiIntegrationAddForm,
	SlackIntegrationAddForm,
	TwilioIntegrationAddForm,
	TelegramIntegrationAddForm,
	ZoomIntegrationAddForm,
	SalesforceIntegrationAddForm,
	KubernetesIntegrationAddForm,
	RedditIntegrationAddForm,
	PipedriveIntegrationAddForm,
	NotionIntegrationAddForm,
	PydanticGatewayIntegrationAddForm,
} from "@components/organisms/configuration/connections/integrations";
import { MicrosoftTeamsIntegrationAddForm } from "@components/organisms/configuration/connections/integrations/microsoft/teams";

export const integrationAddFormComponents: Partial<Record<keyof typeof Integrations, React.ComponentType<any>>> = {
	auth0: Auth0IntegrationAddForm,
	asana: AsanaIntegrationAddForm,
	anthropic: AnthropicIntegrationAddForm,
	github: GithubIntegrationAddForm,
	slack: SlackIntegrationAddForm,
	gmail: GoogleIntegrationAddForm,
	sheets: GoogleIntegrationAddForm,
	calendar: GoogleCalendarIntegrationAddForm,
	drive: GoogleIntegrationAddForm,
	forms: GoogleFormsIntegrationAddForm,
	googlegemini: GoogleGeminiIntegrationAddForm,
	aws: AwsIntegrationAddForm,
	chatgpt: OpenAiIntegrationAddForm,
	twilio: TwilioIntegrationAddForm,
	telegram: TelegramIntegrationAddForm,
	jira: JiraIntegrationAddForm,
	confluence: ConfluenceIntegrationAddForm,
	discord: DiscordIntegrationAddForm,
	hubspot: HubspotIntegrationAddForm,
	zoom: ZoomIntegrationAddForm,
	linear: LinearIntegrationAddForm,
	salesforce: SalesforceIntegrationAddForm,
	microsoft_teams: MicrosoftTeamsIntegrationAddForm,
	youtube: GoogleIntegrationAddForm,
	kubernetes: KubernetesIntegrationAddForm,
	reddit: RedditIntegrationAddForm,
	pipedrive: PipedriveIntegrationAddForm,
	notion: NotionIntegrationAddForm,
	pydanticgw: PydanticGatewayIntegrationAddForm,
};
