import { Integrations } from "@src/enums/components";

import {
	AsanaIntegrationEditForm,
	AnthropicIntegrationEditForm,
	Auth0IntegrationEditForm,
	AwsIntegrationEditForm,
	ConfluenceIntegrationEditForm,
	DiscordIntegrationEditForm,
	GithubIntegrationEditForm,
	GoogleCalendarIntegrationEditForm,
	GoogleFormsIntegrationEditForm,
	GoogleGeminiIntegrationEditForm,
	GoogleIntegrationEditForm,
	HubspotIntegrationEditForm,
	JiraIntegrationEditForm,
	OpenAiIntegrationEditForm,
	SlackIntegrationEditForm,
	TwilioIntegrationEditForm,
	TelegramIntegrationEditForm,
	ZoomIntegrationEditForm,
	LinearIntegrationEditForm,
	SalesforceIntegrationEditForm,
	KubernetesIntegrationEditForm,
	RedditIntegrationEditForm,
	PipedriveIntegrationEditForm,
	NotionIntegrationEditForm,
	PydanticGatewayIntegrationEditForm,
} from "@components/organisms/configuration/connections/integrations";
import { MicrosoftTeamsIntegrationEditForm } from "@components/organisms/configuration/connections/integrations/microsoft/teams";

export const integrationToEditComponent: Partial<Record<keyof typeof Integrations, React.ComponentType<any>>> = {
	[Integrations.auth0]: Auth0IntegrationEditForm,
	[Integrations.asana]: AsanaIntegrationEditForm,
	[Integrations.anthropic]: AnthropicIntegrationEditForm,
	[Integrations.github]: GithubIntegrationEditForm,
	[Integrations.discord]: DiscordIntegrationEditForm,
	[Integrations.jira]: JiraIntegrationEditForm,
	[Integrations.twilio]: TwilioIntegrationEditForm,
	[Integrations.telegram]: TelegramIntegrationEditForm,
	[Integrations.chatgpt]: OpenAiIntegrationEditForm,
	[Integrations.slack]: SlackIntegrationEditForm,
	[Integrations.aws]: AwsIntegrationEditForm,
	[Integrations.googlegemini]: GoogleGeminiIntegrationEditForm,
	[Integrations.confluence]: ConfluenceIntegrationEditForm,
	[Integrations.calendar]: GoogleCalendarIntegrationEditForm,
	[Integrations.sheets]: GoogleIntegrationEditForm,
	[Integrations.gmail]: GoogleIntegrationEditForm,
	[Integrations.drive]: GoogleIntegrationEditForm,
	[Integrations.youtube]: GoogleIntegrationEditForm,
	[Integrations.forms]: GoogleFormsIntegrationEditForm,
	[Integrations.hubspot]: HubspotIntegrationEditForm,
	[Integrations.zoom]: ZoomIntegrationEditForm,
	[Integrations.linear]: LinearIntegrationEditForm,
	[Integrations.salesforce]: SalesforceIntegrationEditForm,
	[Integrations.microsoft_teams]: MicrosoftTeamsIntegrationEditForm,
	[Integrations.kubernetes]: KubernetesIntegrationEditForm,
	[Integrations.reddit]: RedditIntegrationEditForm,
	[Integrations.pipedrive]: PipedriveIntegrationEditForm,
	[Integrations.notion]: NotionIntegrationEditForm,
	[Integrations.pydanticgw]: PydanticGatewayIntegrationEditForm,
};
